package certs

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"net/mail"
	"net/url"
	"strings"
	"sync"
	"time"

	"golang.org/x/text/unicode/norm"
)

// caCertificatePrivateKeyOptions defines configuration options for generating a CA certificate and private key pair.
// This struct is used internally to configure the properties of a self-signed CA certificate.
type caCertificatePrivateKeyOptions struct {
	CommonName   string
	Organization []string
	ValidFrom    time.Time
	ValidFor     time.Duration
	KeyType      KeyType
}

// KeyType enumerates the private key algorithms supported for CA generation. Select one with
// [WithCAKeyType]; the zero value, [KeyTypeRSA2048], is used when unset.
//
// Because [CertificateAuthority.GenerateTLSCertificate] derives each leaf key from the CA's key,
// the KeyType chosen for the CA also determines the algorithm of every certificate it issues.
type KeyType int

const (
	// KeyTypeRSA2048 generates a 2048-bit RSA private key. This is the default and preserves
	// the behaviour of CAs generated before this option existed.
	KeyTypeRSA2048 KeyType = iota
	// KeyTypeECDSAP256 generates an ECDSA private key on the NIST P-256 curve. ECDSA keys are
	// significantly faster to generate than RSA, which benefits dynamic per-host leaf issuance.
	KeyTypeECDSAP256
	// KeyTypeED25519 generates an Ed25519 private key.
	KeyTypeED25519
)

const (
	// defaultCacheMaxAge is the default maximum age of a cached certificate before it is re-issued.
	defaultCacheMaxAge = time.Hour
	// defaultCacheMaxSize is the default maximum number of certificates held in the cache.
	defaultCacheMaxSize = 5
	// defaultLeafCertificateValidity is the validity period of certificates issued dynamically
	// by the SNI-driven TLS configuration.
	defaultLeafCertificateValidity = 24 * time.Hour
)

// CAOption is a function type used to configure the CA certificate and private
// key generated by [GenerateCACertificatePrivateKey] or
// [GenerateCACertificatePrivateKeyPEM] using the functional options pattern.
// Options are applied in order, so later options override earlier ones.
//
// Parameters:
//   - opts (*caCertificatePrivateKeyOptions): A pointer to caCertificatePrivateKeyOptions to be modified.
type CAOption func(opts *caCertificatePrivateKeyOptions)

// A CertificateAuthority generates and signs TLS certificates from a single CA certificate and
// its private key. It issues certificates dynamically for the hostname requested via Server Name
// Indication (SNI) and caches them to avoid re-issuing on every connection; the cache size and
// expiry are configurable (see [WithCacheMaxSize] and
// [WithCacheMaxAge]).
//
// The zero value is not usable: construct a CertificateAuthority with [New] (from an in-memory
// certificate and key), with [NewFromPEM] (from PEM bytes), or generate a
// fresh CA first with [GenerateCACertificatePrivateKey].
//
// A CertificateAuthority is safe for concurrent use by multiple goroutines; the certificate cache
// and the in-flight generation tracking are guarded by internal mutexes.
type CertificateAuthority struct {
	caCertificate           *x509.Certificate
	caCertificatePrivateKey crypto.Signer

	cacheMutex   sync.RWMutex
	cache        map[string]*tlsCertificateCacheEntry
	cacheMaxAge  time.Duration
	cacheMaxSize int

	inflightMutex sync.Mutex
	inflight      map[string]*inflightCall
}

// CACertificate returns a copy of the CA's X.509 certificate.
//
// The returned certificate is a shallow copy, so mutating its fields does not affect the authority.
//
// Returns:
//   - certificate (*x509.Certificate): A copy of the CA's X.509 certificate used for signing TLS
//     certificates, or nil if the authority is nil or uninitialized.
func (ca *CertificateAuthority) CACertificate() (certificate *x509.Certificate) {
	if ca == nil || ca.caCertificate == nil {
		return nil
	}

	certificateCopy := *ca.caCertificate

	return &certificateCopy
}

// CACertificatePrivateKey returns the CA's private key.
//
// Returns:
//   - privateKey (crypto.Signer): The private key corresponding to the CA certificate, implementing
//     crypto.Signer, or nil if the authority is nil or uninitialized.
func (ca *CertificateAuthority) CACertificatePrivateKey() (privateKey crypto.Signer) {
	if ca == nil {
		return nil
	}

	return ca.caCertificatePrivateKey
}

// GenerateTLSCertificate generates a new X.509 TLS certificate and its corresponding private key.
//
// This method creates a private key (matching the CA's key type: RSA, ECDSA, or Ed25519) and a TLS certificate signed by the CA,
// based on the provided configuration options and hostnames. The certificate includes a random serial number, a subject key identifier (SKI),
// and supports key encipherment and digital signatures for server authentication. Hostnames are parsed to determine if they represent
// IP addresses, email addresses, URIs, or DNS names, and are added to the appropriate certificate fields. The certificate's CommonName
// defaults to the first host, and its expiry is clamped to the CA's expiry so a leaf never outlives its CA.
//
// By default the Common Name is the first host, the Organization is empty, the
// extended key usage is server authentication ([x509.ExtKeyUsageServerAuth]),
// the validity period is 365 days from now, and the leaf's key algorithm
// matches the CA's.
//
// Parameters:
//   - hosts ([]string): A slice of hostnames (e.g., DNS names, IPs, emails, or URIs) to include in the certificate.
//   - ofs (...TLSOption): A variadic list of TLSOption functions to configure
//     the certificate's properties (e.g., CommonName, Organization, ValidFrom, ValidFor).
//
// Returns:
//   - certificate (*x509.Certificate): A pointer to the generated X.509 TLS certificate.
//   - privateKey (crypto.Signer): The generated private key, implementing crypto.Signer.
//   - err (error): An error if the authority is uninitialized, the inputs are invalid, or key generation, SKI generation,
//     serial number generation, certificate creation, or parsing fails; otherwise, nil.
func (ca *CertificateAuthority) GenerateTLSCertificate(hosts []string, ofs ...TLSOption) (certificate *x509.Certificate, privateKey crypto.Signer, err error) {
	if ca == nil {
		err = errors.New("invalid input, CertificateAuthority is nil")

		return nil, nil, err
	}

	if ca.caCertificate == nil || ca.caCertificatePrivateKey == nil {
		err = errors.New("invalid input, CertificateAuthority is not initialized")

		return nil, nil, err
	}

	if len(hosts) == 0 {
		err = errors.New("invalid input, hosts list is empty")

		return nil, nil, err
	}

	for _, host := range hosts {
		if host == "" {
			err = errors.New("invalid input, empty hostname in hosts list")

			return nil, nil, err
		}
	}

	opts := &tlsCertificatePrivateKeyOptions{
		CommonName: hosts[0],
		ValidFrom:  time.Now(),
		ValidFor:   365 * 24 * time.Hour,
	}

	for _, f := range ofs {
		f(opts)
	}

	if opts.CommonName == "" {
		err = errors.New("invalid input, CommonName is empty")

		return nil, nil, err
	}

	if opts.ValidFor <= 0 {
		err = fmt.Errorf("invalid input, ValidFor duration must be positive, got %v", opts.ValidFor)

		return nil, nil, err
	}

	switch caKey := ca.caCertificatePrivateKey.(type) {
	case *rsa.PrivateKey:
		privateKey, err = rsa.GenerateKey(rand.Reader, 2048)
		if err != nil {
			err = fmt.Errorf("generating RSA private key (2048 bits): %w", err)

			return nil, nil, err
		}
	case *ecdsa.PrivateKey:
		curve := caKey.Curve
		if curve == nil {
			curve = elliptic.P256()
		}

		privateKey, err = ecdsa.GenerateKey(curve, rand.Reader)
		if err != nil {
			err = fmt.Errorf("generating ECDSA private key (curve %v): %w", curve, err)

			return nil, nil, err
		}
	case ed25519.PrivateKey:
		_, privateKey, err = ed25519.GenerateKey(rand.Reader)
		if err != nil {
			err = fmt.Errorf("generating Ed25519 private key: %w", err)

			return nil, nil, err
		}
	default:
		err = fmt.Errorf("unsupported CA private key type: %T", caKey)

		return nil, nil, err
	}

	publicKey := privateKey.Public()

	serialNumber, err := generateSerialNumber()
	if err != nil {
		err = fmt.Errorf("generating serial number for certificate: %w", err)

		return nil, nil, err
	}

	subjectKeyID, err := generateSubjectKeyID(publicKey)
	if err != nil {
		err = fmt.Errorf("generating subject key ID for public key (type %T): %w", publicKey, err)

		return nil, nil, err
	}

	extKeyUsage := opts.ExtKeyUsage
	if len(extKeyUsage) == 0 {
		extKeyUsage = []x509.ExtKeyUsage{
			x509.ExtKeyUsageServerAuth,
		}
	}

	// Clamp the leaf's expiry to the CA's expiry so an issued certificate never
	// outlives the authority that signed it.
	notAfter := opts.ValidFrom.Add(opts.ValidFor)
	if notAfter.After(ca.caCertificate.NotAfter) {
		notAfter = ca.caCertificate.NotAfter
	}

	template := &x509.Certificate{
		BasicConstraintsValid: true,
		ExtKeyUsage:           extKeyUsage,
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		// Backdate NotBefore by 5 minutes to tolerate modest clock skew between
		// this host and verifying clients.
		NotBefore:    opts.ValidFrom.Add(-5 * time.Minute),
		NotAfter:     notAfter,
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			CommonName:   opts.CommonName,
			Organization: opts.Organization,
		},
		SubjectKeyId: subjectKeyID,
	}

	for _, host := range hosts {
		// Classify each host into the matching Subject Alternative Name field.
		// Order matters: an IP literal, then a bare email address, then a URI
		// (which requires both a scheme and a host), falling back to a DNS name.
		if IP := net.ParseIP(host); IP != nil {
			template.IPAddresses = append(template.IPAddresses, IP)
		} else if email, err := mail.ParseAddress(host); err == nil && email.Address == host {
			template.EmailAddresses = append(template.EmailAddresses, host)
		} else if uriName, err := url.Parse(host); err == nil && uriName.Scheme != "" && uriName.Host != "" {
			template.URIs = append(template.URIs, uriName)
		} else {
			template.DNSNames = append(template.DNSNames, host)
		}
	}

	certificateDER, err := x509.CreateCertificate(rand.Reader, template, ca.caCertificate, publicKey, ca.caCertificatePrivateKey)
	if err != nil {
		err = fmt.Errorf("creating TLS certificate for hosts %v: %w", hosts, err)

		return nil, nil, err
	}

	certificate, err = x509.ParseCertificate(certificateDER)
	if err != nil {
		err = fmt.Errorf("parsing generated TLS certificate: %w", err)

		return nil, nil, err
	}

	return certificate, privateKey, nil
}

// TLSCertificate returns a TLS certificate for the given hostname, generating and caching it on
// first use and serving the cached certificate on subsequent calls.
//
// The hostname is normalized before lookup (port stripped, Unicode NFC folded to lowercase, trailing
// dot removed), and concurrent calls for the same host share a single generation.
//
// The returned bundle chains to the CA certificate: Certificate[0] is the leaf
// certificate, Certificate[1] is the CA certificate, and the Leaf field is
// populated. The cache is configured with [WithCacheMaxAge] and
// [WithCacheMaxSize] on [New].
//
// Parameters:
//   - hostname (string): The hostname to issue the certificate for (e.g., "example.com").
//
// Returns:
//   - certificate (*tls.Certificate): The TLS certificate, including the certificate chain and private key.
//   - err (error): An error if the authority is nil or uninitialized, or certificate generation fails;
//     otherwise, nil.
func (ca *CertificateAuthority) TLSCertificate(hostname string) (certificate *tls.Certificate, err error) {
	if ca == nil {
		err = errors.New("invalid input, CertificateAuthority is nil")

		return nil, err
	}

	if ca.caCertificate == nil || ca.caCertificatePrivateKey == nil {
		err = errors.New("invalid input, CertificateAuthority is not initialized")

		return nil, err
	}

	return ca.getTLSCertificate(hostname)
}

// SignCSR signs a certificate signing request (CSR) with the CA's private key
// and returns the resulting X.509 certificate.
//
// The certificate template is derived from the CSR's public key, subject, and
// subject alternative names, while validity period, extended key usage, and
// subject overrides are applied through the provided options. When no EKU
// options are supplied, the certificate defaults to client authentication
// ([x509.ExtKeyUsageClientAuth]). The certificate's expiry is clamped to the
// CA's expiry so a signed certificate never outlives its CA.
//
// The CSR's signature is verified before signing. The Common Name and
// Organization default to the CSR's subject values and can be overridden with
// [WithTLSCommonName] and [WithTLSOrganization]; the subject alternative names
// (DNS names, IP addresses, email addresses, and URIs) are copied from the CSR.
//
// Parameters:
//   - csr (*x509.CertificateRequest): The parsed CSR to sign.
//   - ofs (...TLSOption): Optional overrides for
//     certificate properties.
//
// Returns:
//   - certificate (*x509.Certificate): The signed certificate.
//   - err (error): An error if the authority is uninitialized, CSR validation fails, or signing fails.
func (ca *CertificateAuthority) SignCSR(csr *x509.CertificateRequest, ofs ...TLSOption) (certificate *x509.Certificate, err error) {
	if ca == nil {
		err = errors.New("invalid input, CertificateAuthority is nil")

		return nil, err
	}

	if ca.caCertificate == nil || ca.caCertificatePrivateKey == nil {
		err = errors.New("invalid input, CertificateAuthority is not initialized")

		return nil, err
	}

	if csr == nil {
		err = errors.New("invalid input, CSR is nil")

		return nil, err
	}

	if err = csr.CheckSignature(); err != nil {
		err = fmt.Errorf("verifying CSR signature: %w", err)

		return nil, err
	}

	opts := &tlsCertificatePrivateKeyOptions{
		CommonName:   csr.Subject.CommonName,
		Organization: csr.Subject.Organization,
		ValidFrom:    time.Now(),
		ValidFor:     365 * 24 * time.Hour,
	}

	for _, f := range ofs {
		f(opts)
	}

	if opts.CommonName == "" {
		err = errors.New("invalid input, CommonName is empty")

		return nil, err
	}

	if opts.ValidFor <= 0 {
		err = fmt.Errorf("invalid input, ValidFor duration must be positive, got %v", opts.ValidFor)

		return nil, err
	}

	extKeyUsage := opts.ExtKeyUsage
	if len(extKeyUsage) == 0 {
		extKeyUsage = []x509.ExtKeyUsage{
			x509.ExtKeyUsageClientAuth,
		}
	}

	serialNumber, err := generateSerialNumber()
	if err != nil {
		err = fmt.Errorf("generating serial number for certificate: %w", err)

		return nil, err
	}

	subjectKeyID, err := generateSubjectKeyID(csr.PublicKey)
	if err != nil {
		err = fmt.Errorf("generating subject key ID for CSR public key: %w", err)

		return nil, err
	}

	// Clamp the certificate's expiry to the CA's expiry so a signed certificate
	// never outlives the authority that signed it.
	notAfter := opts.ValidFrom.Add(opts.ValidFor)
	if notAfter.After(ca.caCertificate.NotAfter) {
		notAfter = ca.caCertificate.NotAfter
	}

	template := &x509.Certificate{
		BasicConstraintsValid: true,
		DNSNames:              csr.DNSNames,
		EmailAddresses:        csr.EmailAddresses,
		ExtKeyUsage:           extKeyUsage,
		IPAddresses:           csr.IPAddresses,
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		NotBefore:             opts.ValidFrom.Add(-5 * time.Minute),
		NotAfter:              notAfter,
		SerialNumber:          serialNumber,
		Subject: pkix.Name{
			CommonName:   opts.CommonName,
			Organization: opts.Organization,
			SerialNumber: csr.Subject.SerialNumber,
			Country:      csr.Subject.Country,
			Province:     csr.Subject.Province,
			Locality:     csr.Subject.Locality,
		},
		SubjectKeyId: subjectKeyID,
		URIs:         csr.URIs,
	}

	certificateDER, err := x509.CreateCertificate(rand.Reader, template, ca.caCertificate, csr.PublicKey, ca.caCertificatePrivateKey)
	if err != nil {
		err = fmt.Errorf("signing CSR: %w", err)

		return nil, err
	}

	certificate, err = x509.ParseCertificate(certificateDER)
	if err != nil {
		err = fmt.Errorf("parsing signed CSR certificate: %w", err)

		return nil, err
	}

	return certificate, nil
}

// TLSConfigOption is a function type used to configure the tls.Config produced by
// [CertificateAuthority.NewTLSConfig] and [CertificateAuthority.NewTLSConfigWithHost].
//
// Parameters:
//   - cfg (*tls.Config): A pointer to the tls.Config to be modified.
type TLSConfigOption func(cfg *tls.Config)

// WithNextProtos sets the ALPN protocols advertised by the TLS configuration.
//
// When unset, the configuration defaults to advertising "h2" and "http/1.1", which suits HTTP
// servers. Call WithNextProtos with no arguments to disable ALPN entirely, which is
// the right choice for non-HTTP servers.
//
// Parameters:
//   - protos (...string): The ALPN protocol identifiers to advertise, in preference order.
//
// Returns:
//   - (TLSConfigOption): A TLSConfigOption that updates the NextProtos field of the config.
func WithNextProtos(protos ...string) TLSConfigOption {
	return func(cfg *tls.Config) {
		cfg.NextProtos = protos
	}
}

// NewTLSConfig creates a TLS configuration for use in a TLS server.
//
// If the authority is nil or uninitialized, the returned configuration fails every handshake with
// an error instead of silently serving TLS without dynamic certificates.
//
// Parameters:
//   - ofs (...TLSConfigOption): A variadic list of TLSConfigOption functions to configure
//     the returned tls.Config (e.g., [WithNextProtos]).
//
// Returns:
//   - cfg (*tls.Config): A pointer to a tls.Config with a dynamic certificate generation function.
func (ca *CertificateAuthority) NewTLSConfig(ofs ...TLSConfigOption) (cfg *tls.Config) {
	// A nil authority behaves as an uninitialized one: the returned configuration
	// fails every handshake with an error instead of silently serving TLS without
	// dynamic certificates.
	if ca == nil {
		ca = &CertificateAuthority{}
	}

	cfg = &tls.Config{
		GetCertificate: func(hello *tls.ClientHelloInfo) (certificate *tls.Certificate, err error) {
			if hello == nil {
				err = errors.New("invalid input, ClientHelloInfo is nil")

				return nil, err
			}

			host := hello.ServerName

			if host == "" {
				err = errors.New("invalid input, missing server name (SNI)")

				return nil, err
			}

			return ca.getTLSCertificate(host)
		},
		MinVersion: tls.VersionTLS12,
		NextProtos: []string{"h2", "http/1.1"},
	}

	for _, f := range ofs {
		f(cfg)
	}

	return cfg
}

// NewTLSConfigWithHost creates a TLS configuration for a specific hostname.
//
// Similar to NewTLSConfig, but allows specifying a default hostname to use when SNI is not provided.
// If the authority is nil or uninitialized, the returned configuration fails every handshake with
// an error instead of silently serving TLS without dynamic certificates.
//
// Parameters:
//   - hostname (string): The default hostname to use if SNI is not provided.
//   - ofs (...TLSConfigOption): A variadic list of TLSConfigOption functions to configure
//     the returned tls.Config (e.g., [WithNextProtos]).
//
// Returns:
//   - cfg (*tls.Config): A pointer to a tls.Config with a dynamic certificate generation function.
func (ca *CertificateAuthority) NewTLSConfigWithHost(hostname string, ofs ...TLSConfigOption) (cfg *tls.Config) {
	// A nil authority behaves as an uninitialized one: the returned configuration
	// fails every handshake with an error instead of silently serving TLS without
	// dynamic certificates.
	if ca == nil {
		ca = &CertificateAuthority{}
	}

	cfg = &tls.Config{
		GetCertificate: func(hello *tls.ClientHelloInfo) (certificate *tls.Certificate, err error) {
			if hello == nil {
				err = errors.New("invalid input, ClientHelloInfo is nil")

				return nil, err
			}

			host := hello.ServerName
			if host == "" {
				host = hostname
			}

			return ca.getTLSCertificate(host)
		},
		MinVersion: tls.VersionTLS12,
		NextProtos: []string{"h2", "http/1.1"},
	}

	for _, f := range ofs {
		f(cfg)
	}

	return cfg
}

// getTLSCertificate retrieves or generates a TLS certificate for the given hostname.
//
// This internal method checks the cache for an existing certificate for the normalized hostname.
// If a valid cached certificate exists (neither older than cacheMaxAge nor expired), it is returned.
// Otherwise, a new certificate is generated and stored in the cache. Concurrent generation for the
// same host is deduplicated: the first caller generates while later callers wait for its result,
// so a burst of simultaneous handshakes pays for a single key generation.
//
// Parameters:
//   - hostname (string): The hostname (e.g., "example.com") for which to retrieve or generate a certificate.
//
// Returns:
//   - certificate (*tls.Certificate): The TLS certificate, including the certificate chain and private key.
//   - err (error): An error if certificate generation fails; otherwise, nil.
func (ca *CertificateAuthority) getTLSCertificate(hostname string) (certificate *tls.Certificate, err error) {
	host := normalizeHost(hostname)

	ca.cacheMutex.RLock()

	if entry, exists := ca.cache[host]; exists && ca.isCacheEntryValid(entry) {
		certificate = entry.certificate

		ca.cacheMutex.RUnlock()

		return certificate, nil
	}

	ca.cacheMutex.RUnlock()

	// Deduplicate concurrent generation for the same host: the first caller
	// (the leader) generates while later callers wait on the in-flight call.
	ca.inflightMutex.Lock()

	if ca.inflight == nil {
		ca.inflight = make(map[string]*inflightCall)
	}

	if call, exists := ca.inflight[host]; exists {
		ca.inflightMutex.Unlock()

		<-call.done

		return call.certificate, call.err
	}

	call := &inflightCall{done: make(chan struct{})}
	ca.inflight[host] = call

	ca.inflightMutex.Unlock()

	certificate, err = ca.generateAndCacheTLSCertificate(host)

	// Writes happen-before close(done), so waiters observe the finished call.
	call.certificate, call.err = certificate, err

	close(call.done)

	ca.inflightMutex.Lock()
	delete(ca.inflight, host)
	ca.inflightMutex.Unlock()

	return certificate, err
}

// generateAndCacheTLSCertificate generates a certificate for the host and stores it in the cache.
//
// Because in-flight generation is deduplicated per host in getTLSCertificate, at most one
// goroutine runs this method for a given host at a time.
//
// Parameters:
//   - host (string): The normalized hostname for which to generate a certificate.
//
// Returns:
//   - certificate (*tls.Certificate): The generated TLS certificate, including the chain and private key.
//   - err (error): An error if certificate generation fails; otherwise, nil.
func (ca *CertificateAuthority) generateAndCacheTLSCertificate(host string) (certificate *tls.Certificate, err error) {
	leafCertificate, leafPrivateKey, err := ca.GenerateTLSCertificate([]string{host}, WithTLSValidFor(defaultLeafCertificateValidity))
	if err != nil {
		err = fmt.Errorf("generating TLS certificate for host %q: %w", host, err)

		return nil, err
	}

	certificate = &tls.Certificate{
		Certificate: [][]byte{
			leafCertificate.Raw,
			ca.caCertificate.Raw,
		},
		PrivateKey: leafPrivateKey,
		Leaf:       leafCertificate,
	}

	ca.cacheMutex.Lock()

	defer ca.cacheMutex.Unlock()

	if ca.cache == nil {
		ca.cache = make(map[string]*tlsCertificateCacheEntry)
	}

	if _, exists := ca.cache[host]; !exists && len(ca.cache) >= ca.cacheMaxSize {
		ca.clearOldCacheEntries()
	}

	ca.cache[host] = &tlsCertificateCacheEntry{
		certificate: certificate,
		createdAt:   time.Now(),
	}

	return certificate, nil
}

// isCacheEntryValid reports whether a cached certificate may still be served: it must be younger
// than the configured maximum age and the certificate itself must not have expired.
//
// Parameters:
//   - entry (*tlsCertificateCacheEntry): The cache entry to validate.
//
// Returns:
//   - valid (bool): True if the entry may be served to clients; otherwise, false.
func (ca *CertificateAuthority) isCacheEntryValid(entry *tlsCertificateCacheEntry) (valid bool) {
	if entry.certificate == nil || entry.certificate.Leaf == nil {
		return false
	}

	return time.Since(entry.createdAt) < ca.cacheMaxAge && time.Now().Before(entry.certificate.Leaf.NotAfter)
}

// clearOldCacheEntries removes the oldest certificate from the cache to make room for new entries.
//
// It identifies the certificate with the earliest creation time and removes it from the cache.
// This is called when the cache reaches its maximum size (cacheMaxSize) to ensure the cache does not grow indefinitely.
func (ca *CertificateAuthority) clearOldCacheEntries() {
	var oldestKey string

	var oldestTime time.Time

	for key, entry := range ca.cache {
		if oldestTime.IsZero() || entry.createdAt.Before(oldestTime) {
			oldestTime = entry.createdAt
			oldestKey = key
		}
	}

	if oldestKey != "" {
		delete(ca.cache, oldestKey)
	}
}

// tlsCertificateCacheEntry represents a cached TLS certificate and its creation time.
// This struct is used internally by CertificateAuthority to store dynamically generated certificates.
type tlsCertificateCacheEntry struct {
	certificate *tls.Certificate
	createdAt   time.Time
}

// inflightCall tracks an in-progress certificate generation for a single hostname so that
// concurrent callers can wait for and share its result instead of generating duplicates.
type inflightCall struct {
	done        chan struct{}
	certificate *tls.Certificate
	err         error
}

// tlsCertificatePrivateKeyOptions defines configuration options for generating a TLS certificate and private key pair.
// This struct is used internally to configure the properties of a TLS certificate signed by the CA.
type tlsCertificatePrivateKeyOptions struct {
	CommonName   string
	Organization []string
	ValidFrom    time.Time
	ValidFor     time.Duration
	ExtKeyUsage  []x509.ExtKeyUsage
}

// TLSOption is a function type used to configure the TLS certificate issued by
// [CertificateAuthority.GenerateTLSCertificate] or
// [CertificateAuthority.SignCSR] using the functional options pattern. Options
// are applied in order, so later options override earlier ones.
//
// Parameters:
//   - opts (*tlsCertificatePrivateKeyOptions): A pointer to tlsCertificatePrivateKeyOptions to be modified.
type TLSOption func(opts *tlsCertificatePrivateKeyOptions)

// WithCACommonName sets the Common Name (CN) for the CA certificate's subject.
//
// The Common Name has no default and is required: generation fails if it is
// unset or empty.
//
// Parameters:
//   - commonName (string): The Common Name to set in the certificate's subject (e.g., "Example Root CA").
//
// Returns:
//   - (CAOption): A CAOption that updates the CommonName field of the options.
func WithCACommonName(commonName string) CAOption {
	return func(opts *caCertificatePrivateKeyOptions) {
		opts.CommonName = commonName
	}
}

// WithCAOrganization sets the Organization field for the CA certificate's subject.
//
// The default is empty: the subject carries no Organization unless this option
// is used.
//
// Parameters:
//   - organization ([]string): A slice of organization names to set in the certificate's subject (e.g., ["Example Org"]).
//
// Returns:
//   - (CAOption): A CAOption that updates the Organization field of the options.
func WithCAOrganization(organization []string) CAOption {
	return func(opts *caCertificatePrivateKeyOptions) {
		opts.Organization = organization
	}
}

// WithCAValidFrom sets the start time for the CA certificate's validity period.
//
// The default is the current time. The certificate's NotBefore is backdated by
// 5 minutes from this time to tolerate clock skew between hosts.
//
// Parameters:
//   - validFrom (time.Time): The time from which the certificate is valid (e.g., time.Now()).
//
// Returns:
//   - (CAOption): A CAOption that updates the ValidFrom field of the options.
func WithCAValidFrom(validFrom time.Time) CAOption {
	return func(opts *caCertificatePrivateKeyOptions) {
		opts.ValidFrom = validFrom
	}
}

// WithCAValidFor sets the duration for the CA certificate's validity period.
//
// The default is 365 days. The duration must be positive: generation returns
// an error otherwise.
//
// Parameters:
//   - validFor (time.Duration): The duration for which the certificate is valid from ValidFrom (e.g., 365*24*time.Hour).
//
// Returns:
//   - (CAOption): A CAOption that updates the ValidFor field of the options.
func WithCAValidFor(validFor time.Duration) CAOption {
	return func(opts *caCertificatePrivateKeyOptions) {
		opts.ValidFor = validFor
	}
}

// WithCAKeyType sets the private key algorithm for the generated CA.
//
// When unset, the CA defaults to KeyTypeRSA2048. Choosing KeyTypeECDSAP256 or KeyTypeED25519
// also makes every leaf certificate issued by the resulting CA use that algorithm, since leaf
// keys match the CA's key type.
//
// Parameters:
//   - keyType (KeyType): The key algorithm to use (KeyTypeRSA2048, KeyTypeECDSAP256, or KeyTypeED25519).
//
// Returns:
//   - (CAOption): A CAOption that updates the KeyType field of the options.
func WithCAKeyType(keyType KeyType) CAOption {
	return func(opts *caCertificatePrivateKeyOptions) {
		opts.KeyType = keyType
	}
}

// GenerateCACertificatePrivateKey generates a new X.509 CA certificate and its corresponding private key.
//
// This function creates a private key (RSA, ECDSA, or Ed25519 based on configuration) and a self-signed CA certificate
// using the functional options pattern. The certificate includes a random serial number, a subject key identifier (SKI),
// and is configured for certificate signing and CRL signing, as per RFC 5280. The validity period starts at ValidFrom
// (defaulting to the current time) and extends for ValidFor (defaulting to 365 days). The Common Name has no default
// and must be set with [WithCACommonName]; the Organization is empty unless set with [WithCAOrganization].
//
// Parameters:
//   - ofs (...CAOption): A variadic list of CAOption functions to configure
//     the certificate's properties (e.g., CommonName, Organization, ValidFrom, ValidFor).
//
// Returns:
//   - certificate (*x509.Certificate): A pointer to the generated X.509 CA certificate.
//   - privateKey (crypto.Signer): The generated private key, implementing crypto.Signer.
//   - err (error): An error if the inputs are invalid or key generation, SKI generation, serial number generation,
//     certificate creation, or parsing fails; otherwise, nil.
func GenerateCACertificatePrivateKey(ofs ...CAOption) (certificate *x509.Certificate, privateKey crypto.Signer, err error) {
	opts := &caCertificatePrivateKeyOptions{
		ValidFrom: time.Now(),
		ValidFor:  365 * 24 * time.Hour,
	}

	for _, f := range ofs {
		f(opts)
	}

	if opts.CommonName == "" {
		err = errors.New("invalid input, CommonName is empty")

		return nil, nil, err
	}

	if opts.ValidFor <= 0 {
		err = fmt.Errorf("invalid input, ValidFor duration must be positive, got %v", opts.ValidFor)

		return nil, nil, err
	}

	switch opts.KeyType {
	case KeyTypeRSA2048:
		privateKey, err = rsa.GenerateKey(rand.Reader, 2048)
		if err != nil {
			err = fmt.Errorf("generating RSA private key (2048 bits): %w", err)

			return nil, nil, err
		}
	case KeyTypeECDSAP256:
		privateKey, err = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			err = fmt.Errorf("generating ECDSA private key (curve P-256): %w", err)

			return nil, nil, err
		}
	case KeyTypeED25519:
		_, privateKey, err = ed25519.GenerateKey(rand.Reader)
		if err != nil {
			err = fmt.Errorf("generating Ed25519 private key: %w", err)

			return nil, nil, err
		}
	default:
		err = fmt.Errorf("invalid input, unsupported CA key type: %d", opts.KeyType)

		return nil, nil, err
	}

	publicKey := privateKey.Public()

	serialNumber, err := generateSerialNumber()
	if err != nil {
		err = fmt.Errorf("generating serial number for CA certificate: %w", err)

		return nil, nil, err
	}

	subjectKeyID, err := generateSubjectKeyID(publicKey)
	if err != nil {
		err = fmt.Errorf("generating subject key ID for public key (type %T): %w", publicKey, err)

		return nil, nil, err
	}

	template := &x509.Certificate{
		BasicConstraintsValid: true,
		IsCA:                  true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		// Backdate NotBefore by 5 minutes to tolerate modest clock skew between
		// this host and verifying clients.
		NotBefore:    opts.ValidFrom.Add(-5 * time.Minute),
		NotAfter:     opts.ValidFrom.Add(opts.ValidFor),
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			CommonName:   opts.CommonName,
			Organization: opts.Organization,
		},
		SubjectKeyId: subjectKeyID,
	}

	certificateDER, err := x509.CreateCertificate(rand.Reader, template, template, publicKey, privateKey)
	if err != nil {
		err = fmt.Errorf("creating self-signed CA certificate: %w", err)

		return nil, nil, err
	}

	certificate, err = x509.ParseCertificate(certificateDER)
	if err != nil {
		err = fmt.Errorf("parsing generated CA certificate: %w", err)

		return nil, nil, err
	}

	return certificate, privateKey, nil
}

// GenerateCACertificatePrivateKeyPEM generates a new X.509 CA certificate and private key, returning them in PEM format.
//
// This function wraps [GenerateCACertificatePrivateKey] and converts the resulting certificate and private key to PEM format.
//
// A Common Name option is required, as documented for
// [GenerateCACertificatePrivateKey]. The certificate is encoded in a
// "CERTIFICATE" block; the private key block type depends on the key
// algorithm: "RSA PRIVATE KEY" for RSA, "EC PRIVATE KEY" for ECDSA, and
// "PRIVATE KEY" (PKCS#8) for Ed25519.
//
// Parameters:
//   - ofs (...CAOption): A variadic list of CAOption functions to configure
//     the certificate's properties (e.g., CommonName, Organization, ValidFrom, ValidFor).
//
// Returns:
//   - certificateBytes ([]byte): The PEM-encoded CA certificate.
//   - privateKeyBytes ([]byte): The PEM-encoded private key.
//   - err (error): An error if generation or PEM encoding fails; otherwise, nil.
func GenerateCACertificatePrivateKeyPEM(ofs ...CAOption) (certificateBytes, privateKeyBytes []byte, err error) {
	certificate, privateKey, err := GenerateCACertificatePrivateKey(ofs...)
	if err != nil {
		err = fmt.Errorf("generating CA certificate and private key: %w", err)

		return nil, nil, err
	}

	certificateBytes, err = CertificateToPEM(certificate)
	if err != nil {
		err = fmt.Errorf("converting CA certificate to PEM format: %w", err)

		return nil, nil, err
	}

	privateKeyBytes, err = PrivateKeyToPEM(privateKey)
	if err != nil {
		err = fmt.Errorf("converting CA private key to PEM format (type %T): %w", privateKey, err)

		return nil, nil, err
	}

	return certificateBytes, privateKeyBytes, nil
}

// CertificateToPEM converts an X.509 certificate to PEM format.
//
// The certificate is encoded as a PEM block with type "CERTIFICATE", as per RFC 7468. The resulting PEM data
// is returned as a byte slice for further use (e.g., writing to a file or network).
//
// Parameters:
//   - certificate (*x509.Certificate): A pointer to the X.509 certificate to convert.
//
// Returns:
//   - raw ([]byte): A byte slice containing the PEM-encoded certificate.
//   - err (error): An error if the certificate is nil or has no raw data; otherwise, nil.
func CertificateToPEM(certificate *x509.Certificate) (raw []byte, err error) {
	if certificate == nil {
		err = errors.New("invalid input, certificate is nil")

		return nil, err
	}

	if len(certificate.Raw) == 0 {
		err = errors.New("invalid input, certificate raw data is empty")

		return nil, err
	}

	block := &pem.Block{
		Type:  "CERTIFICATE",
		Bytes: certificate.Raw,
	}

	return pem.EncodeToMemory(block), nil
}

// PrivateKeyToPEM converts a private key to PEM format.
//
// The private key is marshaled to the appropriate format (PKCS#1 for RSA, EC for ECDSA, PKCS#8 for Ed25519) and encoded
// as a PEM block with type "RSA PRIVATE KEY", "EC PRIVATE KEY", or "PRIVATE KEY", as per RFC 7468. The resulting PEM data
// is returned as a byte slice.
//
// Parameters:
//   - key (crypto.Signer): The private key to convert, implementing crypto.Signer.
//
// Returns:
//   - raw ([]byte): A byte slice containing the PEM-encoded private key.
//   - err (error): An error if the key is nil, marshaling fails, or the key type is unsupported; otherwise, nil.
func PrivateKeyToPEM(key crypto.Signer) (raw []byte, err error) {
	if key == nil {
		err = errors.New("invalid input, private key is nil")

		return nil, err
	}

	var blockType string

	var keyBytes []byte

	switch k := key.(type) {
	case *rsa.PrivateKey:
		blockType = "RSA PRIVATE KEY"
		keyBytes = x509.MarshalPKCS1PrivateKey(k)
	case *ecdsa.PrivateKey:
		blockType = "EC PRIVATE KEY"

		keyBytes, err = x509.MarshalECPrivateKey(k)
		if err != nil {
			err = fmt.Errorf("marshaling ECDSA private key: %w", err)

			return nil, err
		}
	case ed25519.PrivateKey:
		blockType = "PRIVATE KEY"

		keyBytes, err = x509.MarshalPKCS8PrivateKey(k)
		if err != nil {
			err = fmt.Errorf("marshaling Ed25519 private key: %w", err)

			return nil, err
		}
	default:
		err = fmt.Errorf("unsupported private key type: %T", key)

		return nil, err
	}

	block := &pem.Block{
		Type:  blockType,
		Bytes: keyBytes,
	}

	return pem.EncodeToMemory(block), nil
}

// WithTLSCommonName sets the Common Name (CN) for the TLS certificate's subject.
//
// The default is the first host for
// [CertificateAuthority.GenerateTLSCertificate] and the CSR's Common Name for
// [CertificateAuthority.SignCSR]. It must not be empty.
//
// Parameters:
//   - commonName (string): The Common Name to set in the certificate's subject (e.g., "example.com").
//
// Returns:
//   - (TLSOption): A TLSOption that updates the CommonName field of the options.
func WithTLSCommonName(commonName string) TLSOption {
	return func(opts *tlsCertificatePrivateKeyOptions) {
		opts.CommonName = commonName
	}
}

// WithTLSOrganization sets the Organization field for the TLS certificate's subject.
//
// The default is empty for [CertificateAuthority.GenerateTLSCertificate] and
// the CSR's Organization for [CertificateAuthority.SignCSR].
//
// Parameters:
//   - organization ([]string): A slice of organization names to set in the certificate's subject (e.g., ["My Org"]).
//
// Returns:
//   - (TLSOption): A TLSOption that updates the Organization field of the options.
func WithTLSOrganization(organization []string) TLSOption {
	return func(opts *tlsCertificatePrivateKeyOptions) {
		opts.Organization = organization
	}
}

// WithTLSValidFrom sets the start time for the TLS certificate's validity period.
//
// The default is the current time. The certificate's NotBefore is backdated by
// 5 minutes from this time to tolerate clock skew, and its NotAfter is clamped
// to the CA's expiry.
//
// Parameters:
//   - validFrom (time.Time): The time from which the certificate is valid (e.g., time.Now()).
//
// Returns:
//   - (TLSOption): A TLSOption that updates the ValidFrom field of the options.
func WithTLSValidFrom(validFrom time.Time) TLSOption {
	return func(opts *tlsCertificatePrivateKeyOptions) {
		opts.ValidFrom = validFrom
	}
}

// WithTLSValidFor sets the duration for the TLS certificate's validity period.
//
// The default is 365 days. The duration must be positive, and the resulting
// expiry is clamped to the CA's NotAfter so an issued certificate never
// outlives the authority that signed it.
//
// Parameters:
//   - validFor (time.Duration): The duration for which the certificate is valid from ValidFrom (e.g., 24*time.Hour).
//
// Returns:
//   - (TLSOption): A TLSOption that updates the ValidFor field of the options.
func WithTLSValidFor(validFor time.Duration) TLSOption {
	return func(opts *tlsCertificatePrivateKeyOptions) {
		opts.ValidFor = validFor
	}
}

// WithTLSExtKeyUsage sets the extended key usages for the TLS certificate.
//
// When unset, the default depends on the issuing method:
// [x509.ExtKeyUsageServerAuth] for certificates issued by
// [CertificateAuthority.GenerateTLSCertificate], and
// [x509.ExtKeyUsageClientAuth] for certificates signed by
// [CertificateAuthority.SignCSR].
//
// Pass [x509.ExtKeyUsageClientAuth] explicitly to issue client certificates
// for mutual TLS.
//
// Parameters:
//   - usages (...x509.ExtKeyUsage): One or more extended key usages to set on the certificate.
//
// Returns:
//   - (TLSOption): A TLSOption that updates the ExtKeyUsage field of the options.
func WithTLSExtKeyUsage(usages ...x509.ExtKeyUsage) TLSOption {
	return func(opts *tlsCertificatePrivateKeyOptions) {
		opts.ExtKeyUsage = usages
	}
}

// certificateAuthorityOptions defines configuration options for a CertificateAuthority.
// This struct is used internally to configure the in-memory certificate cache.
type certificateAuthorityOptions struct {
	CacheMaxAge  time.Duration
	CacheMaxSize int
}

// AuthorityOption is a function type used to configure a [CertificateAuthority]
// created by [New] or [NewFromPEM] using the functional options pattern.
// Options are applied in order, so later options override earlier ones.
//
// Parameters:
//   - opts (*certificateAuthorityOptions): A pointer to certificateAuthorityOptions to be modified.
type AuthorityOption func(opts *certificateAuthorityOptions)

// WithCacheMaxAge sets the maximum age of cached certificates before they expire.
//
// The default is 1 hour, and the age must be positive: [New] returns an error
// otherwise. It governs the cache used by the SNI-driven
// [CertificateAuthority.NewTLSConfig] path and
// [CertificateAuthority.TLSCertificate].
//
// Parameters:
//   - maxAge (time.Duration): The maximum age for cached certificates (e.g., 1*time.Hour).
//
// Returns:
//   - (AuthorityOption): A AuthorityOption that updates the CacheMaxAge field of the options.
func WithCacheMaxAge(maxAge time.Duration) AuthorityOption {
	return func(opts *certificateAuthorityOptions) {
		opts.CacheMaxAge = maxAge
	}
}

// WithCacheMaxSize sets the maximum number of certificates to store in the cache.
//
// The default is 5 entries, and the size must be positive: [New] returns an
// error otherwise. It governs the cache used by the SNI-driven
// [CertificateAuthority.NewTLSConfig] path and
// [CertificateAuthority.TLSCertificate].
//
// Parameters:
//   - maxSize (int): The maximum number of cached certificates (e.g., 1024).
//
// Returns:
//   - (AuthorityOption): A AuthorityOption that updates the CacheMaxSize field of the options.
func WithCacheMaxSize(maxSize int) AuthorityOption {
	return func(opts *certificateAuthorityOptions) {
		opts.CacheMaxSize = maxSize
	}
}

// New initializes a new CertificateAuthority with the provided CA certificate and private key.
//
// It verifies that the certificate is configured as a CA, has the necessary key usage for certificate
// signing, and that the private key matches the certificate's public key (RSA, ECDSA, or Ed25519).
// The cache is initialized with a default maximum age of 1 hour and maximum size of 5 entries, both of
// which can be overridden via [AuthorityOption] options.
//
// Parameters:
//   - caCertificate (*x509.Certificate): A pointer to the X.509 CA certificate.
//   - caPrivateKey (crypto.Signer): The private key corresponding to the CA certificate, implementing crypto.Signer.
//   - ofs (...AuthorityOption): A variadic list of options to configure the certificate cache.
//
// Returns:
//   - ca (*CertificateAuthority): A pointer to the initialized CertificateAuthority.
//   - err (error): An error if the CA certificate or private key is invalid, mismatched, or incompatible; otherwise, nil.
func New(caCertificate *x509.Certificate, caPrivateKey crypto.Signer, ofs ...AuthorityOption) (ca *CertificateAuthority, err error) {
	if caCertificate == nil {
		err = errors.New("invalid input, CA certificate is nil")

		return nil, err
	}

	if !caCertificate.IsCA {
		err = errors.New("invalid input, certificate is not configured as a CA (IsCA is false)")

		return nil, err
	}

	if (caCertificate.KeyUsage & x509.KeyUsageCertSign) == 0 {
		err = errors.New("invalid input, CA certificate lacks KeyUsageCertSign")

		return nil, err
	}

	if caPrivateKey == nil {
		err = errors.New("invalid input, CA private key is nil")

		return nil, err
	}

	switch publicKey := caCertificate.PublicKey.(type) {
	case *rsa.PublicKey:
		privateKey, ok := caPrivateKey.(*rsa.PrivateKey)
		if !ok {
			err = fmt.Errorf("invalid input, certificate public key is RSA, but private key is %T", caPrivateKey)

			return nil, err
		}

		if !publicKey.Equal(&privateKey.PublicKey) {
			err = errors.New("invalid input, CA private key does not match the certificate's public key")

			return nil, err
		}
	case *ecdsa.PublicKey:
		privateKey, ok := caPrivateKey.(*ecdsa.PrivateKey)
		if !ok {
			err = fmt.Errorf("invalid input, certificate public key is ECDSA, but private key is %T", caPrivateKey)

			return nil, err
		}

		if !publicKey.Equal(&privateKey.PublicKey) {
			err = errors.New("invalid input, CA private key does not match the certificate's public key")

			return nil, err
		}
	case ed25519.PublicKey:
		privateKey, ok := caPrivateKey.(ed25519.PrivateKey)
		if !ok {
			err = fmt.Errorf("invalid input, certificate public key is Ed25519, but private key is %T", caPrivateKey)

			return nil, err
		}

		if !publicKey.Equal(privateKey.Public()) {
			err = errors.New("invalid input, CA private key does not match the certificate's public key")

			return nil, err
		}
	default:
		err = fmt.Errorf("unsupported certificate public key type: %T", publicKey)

		return nil, err
	}

	opts := &certificateAuthorityOptions{
		CacheMaxAge:  defaultCacheMaxAge,
		CacheMaxSize: defaultCacheMaxSize,
	}

	for _, f := range ofs {
		f(opts)
	}

	if opts.CacheMaxAge <= 0 {
		err = fmt.Errorf("invalid input, cache max age must be positive, got %v", opts.CacheMaxAge)

		return nil, err
	}

	if opts.CacheMaxSize <= 0 {
		err = fmt.Errorf("invalid input, cache max size must be positive, got %d", opts.CacheMaxSize)

		return nil, err
	}

	ca = &CertificateAuthority{
		caCertificate:           caCertificate,
		caCertificatePrivateKey: caPrivateKey,
		cache:                   make(map[string]*tlsCertificateCacheEntry),
		cacheMaxAge:             opts.CacheMaxAge,
		cacheMaxSize:            opts.CacheMaxSize,
		inflight:                make(map[string]*inflightCall),
	}

	return ca, nil
}

// NewFromPEM initializes a new CertificateAuthority from PEM-encoded certificate and private key bytes.
//
// It parses the certificate and private key from the provided byte slices, supporting PKCS#1, PKCS#8, and ECDSA private key formats.
// The parsed certificate and private key are then used to initialize a CertificateAuthority.
//
// The certificate must be in a "CERTIFICATE" PEM block, and the private key in
// an "RSA PRIVATE KEY" (PKCS#1), "EC PRIVATE KEY" (SEC 1), or "PRIVATE KEY"
// (PKCS#8) block. The parsed pair is passed to [New], so all of [New]'s
// validation and options apply.
//
// Parameters:
//   - caCertificateBytes ([]byte): The PEM-encoded CA certificate bytes.
//   - caPrivateKeyBytes ([]byte): The PEM-encoded private key bytes.
//   - ofs (...AuthorityOption): A variadic list of options to configure the certificate cache.
//
// Returns:
//   - ca (*CertificateAuthority): A pointer to the initialized CertificateAuthority.
//   - err (error): An error if parsing or initialization fails; otherwise, nil.
func NewFromPEM(caCertificateBytes, caPrivateKeyBytes []byte, ofs ...AuthorityOption) (ca *CertificateAuthority, err error) {
	if len(caCertificateBytes) == 0 {
		err = errors.New("invalid input, CA certificate bytes are empty")

		return nil, err
	}

	if len(caPrivateKeyBytes) == 0 {
		err = errors.New("invalid input, CA private key bytes are empty")

		return nil, err
	}

	certBlock, _ := pem.Decode(caCertificateBytes)
	if certBlock == nil {
		err = errors.New("decoding PEM block for CA certificate: invalid or malformed PEM data")

		return nil, err
	}

	if certBlock.Type != "CERTIFICATE" {
		err = fmt.Errorf("invalid PEM block type for CA certificate: got %q, expected 'CERTIFICATE'", certBlock.Type)

		return nil, err
	}

	caCertificate, err := x509.ParseCertificate(certBlock.Bytes)
	if err != nil {
		err = fmt.Errorf("parsing X.509 certificate from PEM data: %w", err)

		return nil, err
	}

	keyBlock, _ := pem.Decode(caPrivateKeyBytes)
	if keyBlock == nil {
		err = errors.New("decoding PEM block for private key: invalid or malformed PEM data")

		return nil, err
	}

	var caPrivateKey crypto.Signer

	switch keyBlock.Type {
	case "RSA PRIVATE KEY":
		var key *rsa.PrivateKey

		key, err = x509.ParsePKCS1PrivateKey(keyBlock.Bytes)
		if err != nil {
			err = fmt.Errorf("parsing RSA private key from PEM data: %w", err)

			return nil, err
		}

		caPrivateKey = key
	case "EC PRIVATE KEY":
		var key *ecdsa.PrivateKey

		key, err = x509.ParseECPrivateKey(keyBlock.Bytes)
		if err != nil {
			err = fmt.Errorf("parsing ECDSA private key from PEM data: %w", err)

			return nil, err
		}

		caPrivateKey = key
	case "PRIVATE KEY":
		var key any

		key, err = x509.ParsePKCS8PrivateKey(keyBlock.Bytes)
		if err != nil {
			err = fmt.Errorf("parsing PKCS#8 private key from PEM data: %w", err)

			return nil, err
		}

		signer, ok := key.(crypto.Signer)
		if !ok {
			err = fmt.Errorf("private key of type %T does not implement crypto.Signer", key)

			return nil, err
		}

		caPrivateKey = signer
	default:
		err = fmt.Errorf("unsupported PEM block type for private key: got %q, expected 'RSA PRIVATE KEY', 'EC PRIVATE KEY', or 'PRIVATE KEY'", keyBlock.Type)

		return nil, err
	}

	return New(caCertificate, caPrivateKey, ofs...)
}

// generateSerialNumber creates a random serial number for use in X.509 certificates.
//
// Serial numbers are unique identifiers for certificates, as required by RFC 5280. This function generates a
// cryptographically secure random number with a maximum bit length of 128 bits, ensuring compliance with common
// certificate authority requirements.
//
// Returns:
//   - serialNumber (*big.Int): A pointer to a big.Int representing the generated serial number.
//   - err (error): An error if random number generation fails; otherwise, nil.
func generateSerialNumber() (serialNumber *big.Int, err error) {
	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)

	serialNumber, err = rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		err = fmt.Errorf("generating random serial number (128-bit): %w", err)

		return nil, err
	}

	return serialNumber, nil
}

// generateSubjectKeyID computes a Subject Key Identifier (SKI) from a given public key.
//
// The Subject Key Identifier is a SHA-256 hash of the public key's PKIX-encoded form, as specified in RFC 5280,
// section 4.2.1.2. It is used to uniquely identify a public key in an X.509 certificate.
//
// Parameters:
//   - publicKey (crypto.PublicKey): The cryptographic public key (e.g., *rsa.PublicKey) to generate the SKI for.
//
// Returns:
//   - ski ([]byte): A byte slice containing the SHA-256 hash of the marshaled public key.
//   - err (error): An error if the public key is nil, marshaling fails, or the marshaled key is empty; otherwise, nil.
func generateSubjectKeyID(publicKey crypto.PublicKey) (ski []byte, err error) {
	if publicKey == nil {
		err = errors.New("invalid input, public key is nil")

		return nil, err
	}

	pkixPub, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		err = fmt.Errorf("marshaling public key (type %T) to PKIX format: %w", publicKey, err)

		return nil, err
	}

	if len(pkixPub) == 0 {
		err = fmt.Errorf("invalid public key (type %T), marshaled PKIX data is empty", publicKey)

		return nil, err
	}

	sum := sha256.Sum256(pkixPub)

	return sum[:], nil
}

// normalizeHost normalizes a hostname for use as a cache key and certificate host.
//
// It removes any port number, applies Unicode NFC normalization, folds to lowercase, and strips a
// single trailing dot. DNS names are case-insensitive and the trailing dot marks the fully qualified
// form of the same name, so folding both away lets "Example.com.", "example.com", and
// "example.com:443" converge on a single cached certificate.
//
// Parameters:
//   - unnormalized (string): The hostname to normalize (e.g., "example.com:443").
//
// Returns:
//   - normalized (string): The normalized hostname (e.g., "example.com").
func normalizeHost(unnormalized string) (normalized string) {
	normalized = unnormalized

	if host, _, err := net.SplitHostPort(unnormalized); err == nil {
		normalized = host
	}

	normalized = strings.TrimSuffix(strings.ToLower(norm.NFC.String(normalized)), ".")

	return normalized
}
